eureka:
  client:
    service-url:
      defauultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
server:
  port: ${PORT:0}
  
spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active:
    - test

management:
  endpoints:
    web:
      exposure:
        include: '*'
